---
abstract: 'Easy installation of ffmpeg'
author:
  - 'Torsten Raudssus <torsten@raudss.us>'
build_requires: {}
configure_requires:
  Alien::Base: 0
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-ffmpeg
provides:
  Alien::ffmpeg:
    file: lib/Alien/ffmpeg.pm
    version: 0.001
requires:
  Alien::Base: 0
  File::ShareDir: 1.00
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
